spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/studentdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    url: jdbc:postgresql://localhost:5432/studentdb
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true
server:
  port: 8080